channels:
  - conda-forge
dependencies:
  - appmode
  - pip
    - numpy
    - scipy
    - matplotlib
    - jupyter-book
    - qiskit
    - qiskit-nature
    - pyscf
    - geometric
    - pyberny
    - ipywidgets
    - py3Dmol
# for development only
#    - ghp-import

